sudo: required
os:
- linux
- osx
language: node_js
node_js:
- node
- '9'
- '8'
cache:
  directories:
  - "$HOME/.npm"
before_install:
- npm install -g npm@latest
install:
- npm install
before_script:
- npm run build
script:
- npm run lint
- npm run test
after_success: npm run coverage